#cp -r $1.pot  cpp.po  
#cp -r $1.pot  fil.po  
#cp -r $1.pot  ja.po  
#cp -r $1.pot  mvo.po  
#cp -r $1.pot  pt_BR.po  
cp -r $1.pot  sv.po   
cp -r $1.pot  ur.po
#cp -r $1.pot  af.po  
#cp -r $1.pot  cs.po   
#cp -r $1.pot  fr.po   
#cp -r $1.pot  km.po   
#cp -r $1.pot  na.po   
#cp -r $1.pot  qu.po     
#cp -r $1.pot  w.po   
cp -r $1.pot  vi.po
#cp -r $1.pot  am.po  
cp -r $1.pot  de.po   
cp -r $1.pot  gu.po   
#cp -r $1.pot  kn.po   
cp -r $1.pot  nb.po   
#cp -r $1.pot  ro.po     
#cp -r $1.pot  ta.po   
#cp -r $1.pot  wa.po
#cp -r $1.pot  ar.po  
#cp -r $1.pot  en.po
#cp -r $1.pot  hi.po
#cp -r $1.pot  lv.po
#cp -r $1.pot  zh_CN.po
cp -r $1.pot  th.po 
cp -r $1.pot  rw.po
cp -r $1.pot  nl.po
cp -r $1.pot  kos.po
cp -r $1.pot  he.po
cp -r $1.pot  el.po
#cp -r $1.pot  yo.po
#cp -r $1.pot  te.po
cp -r $1.pot  ru.po
#cp -r $1.pot  ne.po
cp -r $1.pot  ko.po
#cp -r $1.pot  ha.po
#cp -r $1.pot  dz.po    
#cp -r $1.pot  ar_SY.po  
cp -r $1.pot  ay.po       
cp -r $1.pot  sd.po
cp -r $1.pot  ton.po
#cp -r $1.pot  zh_TW.po
cp -r $1.pot  pis.po
cp -r $1.pot  sl.po
#cp -r $1.pot  tvl.po
#cp -r $1.pot  fa_AF.po
#cp -r $1.pot ig.po 
#cp -r $1.pot nn.po
cp -r $1.pot pis.po
#cp -r $1.pot ml.po 
#cp -r $1.pot  hy.po 
#cp -r $1.pot fa.po 
cp -r $1.pot tr.po
#cp -r $1.pot sk.po
#cp -r $1.pot pap.po
#cp -r $1.pot mk.po
cp -r $1.pot hu.po
#cp -r $1.pot es.po
#cp -r $1.pot tpi.po
cp -r $1.pot si.po
cp -r $1.pot pa.po
cp -r $1.pot mg.po
#cp -r $1.pot ht.po
#cp -r $1.pot en_US.po
#cp -r $1.pot bg.po    
#cp -r $1.pot bi.po   
#cp -r $1.pot bn.po   
cp -r $1.pot bn_IN.po     
#cp -r $1.pot bs.po    
#cp -r $1.pot ca.po   
#cp -r $1.pot uk.po
#cp -r $1.pot st.po
#cp -r $1.pot pt.po
#cp -r $1.pot ms.po
#cp -r $1.pot it.po
#cp -r $1.pot fi.po
cp -r $1.pot ug.po
cp -r $1.pot sq.po
cp -r $1.pot ps.po
#cp -r $1.pot  mr.po
cp -r $1.pot is.po
cp -r $1.pot ff.po
#cp -r $1.pot tzo.po
#cp -r $1.pot sm.po
cp -r $1.pot pl.po
#cp -r $1.pot mn.po 




